### ISSUE TITLE
Hacer una funcion que devuelva un objeto a partir de parametros de una url

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#15]
Vamos a hacer una funcion en javascript generica que haga lo siguiente:
- Lea el objeto `location.search` de una pagina
- Descomponga los elementos en propiedades de un objeto

La funcion debera recibir un `string` como parametro y devolver un objeto con tantas propiedades como valores tenga nuestro `string`; considerando que el `string` es un query string de una url.

Ejemplo, si tenemos la url 

```
file:///home/mleyzaola/docs/ShowMovie/app/select_genre.html?genre=Drama&id=3
```

llamariamos nuestra funcion asi:

```
getQueryObject("?genre=Drama&id=3")
```

Y el resultado que nos devolveria la funcion seria este:

```
Object {genre: "Drama", id: "3"}
```

Esta funcion esta relacionada con resolver el issue #14

**Comment by mauleyzaola** [comment]
@lextes si estas trabajando en esta issue recuerda ponerle el label `in progress` :smile:

**Comment by lextes** [comment]
PR #18

**Comment by mauleyzaola** [comment]
PR: #18
