### ISSUE TITLE
Funcion que devuelva una base de datos de peliculas

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#17]
Basandote en este query

```
http://www.imdb.com/search/title?genres=comedy&num_votes=5000,&title_type=feature&user_rating=8.0,10
```
- Cambia los generos de la funcion `readGenres()` a que coincidan con los nombres de generos de IMDB
- Ingresa manualmente a las 5 peliculas que aparecen hasta arriba de cada genero (en realidad puedes escoger cualquiera, pero no pierdas tiempo en ello) y captura los siguientes datos:

```
url -> la url a la pelicula
imageUrl -> la url del poster miniatura que aparece cuando abres la pelicula (todas las url deben devolver el mismo tamanio)
title -> el titulo de la pelicula
year -> el anio que aparece en parentesis al lado del titulo
summary -> la sipnosis que aparece debajo del titulo (suelen ser dos parrafos mas o menos)
genre -> el genero al que pertence la pelicula, segun tu query de imdb (la url)
```

Con esta informacion, vamos a generar una funcion de 4 generos x 5 peliculas = 20 objetos, mismos que devolvera la funcion en un arreglo.

Esta funcion va a simular que es un backend (de momento tenemos un archivo estatico nada mas).

Tiempo aproximado: 1 hr (dependera de tu habilidad para hacer copy/paste basicamente), he calculado 3 min para cada pelicula.

Asegurate que entiendes bien lo que hay que hacer antes de empezar a trabajar.

La funcion debera llamarse `getMovies()` y estara en nuestro archivo `app/js/app/app.js` como el resto de las funciones.

**Comment by lextes** [comment]
pr: #25
