### ISSUE TITLE
Aplicar bootstrap a la pagina index.html

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#28]
El titulo de la pelicula debe ser un `div` con una clase css `alert alert-info`

Y todo el `div` que contiene cada pelicula debe ocupar la mitad de la pantalla `col-lg-6`

**Comment by mauleyzaola** [comment]
Debes llegar a algo similar a esto

![image](https://cloud.githubusercontent.com/assets/1648558/15445390/473d4c4c-1ec3-11e6-8558-56713a138dd0.png)

**Comment by lextes** [comment]
PR: #30
