### ISSUE TITLE
Crear UI

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#3]
Basandote en el mockup que aparece abajo, crear el html necesario

![image](https://cloud.githubusercontent.com/assets/1648558/13970835/f15d621c-f050-11e5-8c03-511649bad747.png)
1. Los elementos del dropdown no los coloques manualmente, deben de crearse con JS
2. El texto `Pop` que aparece debajo tampoco lo escribas a mano, simplemente deja un elemento `<span></span>` para tal fin

**Comment by mauleyzaola** [comment]
El codigo que resulte de esta issue, guardarlo en `app/select_genre.html`

**Comment by mauleyzaola** [comment]
Tiempo estimado para hacer esta issue: 20 min

**Comment by lextes** [comment]
Deje la estructura HTML lista 
![image](https://cloud.githubusercontent.com/assets/16492764/13974661/1eeb8a0a-f084-11e5-8844-c34f05878c33.png)

**Comment by lextes** [comment]
PR: #5
