### ISSUE TITLE
No se cargan los generos en la pagina

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#7]
Consideremos el teorico escenario donde hemos contratado a un desarrollador de javascript que nos dio parte del codigo necesario para llenar los generos del `select` en el UI. Por desgracia esta persona nada mas trabajo con nosotros un dia y no termino su trabajo.

Fue despedido en cuanto nos dimos cuenta que no tiene conocimiento de la metodologia de git/github y no nos interesa tener en nuestro equipo alguien con esas carencias :smile: 

Sin embargo, aqui tenemos lo que esta persona pudo avanzar en su unico dia de trabajo en Lextes, SA. Vamos aprovechar su codigo, agregandolo al final del archivo `app/js/app/app.js`:

```

function addOptions(d, data){
    for(var i=0; i<data.length; i++){
        var opt = document.createElement('option');
        opt.text = data[i];
        d.add(opt);
    }
}

var dropdown = document.getElementById('dropdown');

addOptions(dropdown, readGenres());
```

Aunque aparentemente el codigo esta bien, cuando abres la pagina suceden dos cosas que parecen un bug:
- Aparece un error en la consola

![image](https://cloud.githubusercontent.com/assets/1648558/14031091/c76f8580-f1d0-11e5-9b8f-27a296005f39.png)
- El `select` no muestra los generos que estan en la funcion `readGenres()`, que era finalmente la idea

Por favor resuelve ambos errores.

**Comment by mauleyzaola** [comment]
Como tip te comento que el codigo javascript no tiene ningun error, es decir, no hay nada que hacer ahi. El problema es en el codigo html

**Comment by mauleyzaola** [comment]
Tiempo aproximado de resolucion: 30 min

**Comment by lextes** [comment]
PR #10

**Comment by mauleyzaola** [comment]
@lextes Lo reviso ahora mismo

**Comment by mauleyzaola** [comment]
@lextes Bien, continua con los demas por favor. Voy a salir al cine, vuelvo en 3 hrs.

**Comment by mauleyzaola** [comment]
Ah y cierra este issue, no lo hizo automaticamente :smile:
