### ISSUE TITLE
No seleccionar ningun genero al abrir la pagina

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#8]
Suponiendo que #7 ya esta resuelta, ahora se muestran correctamente los generos en el `select` cuando abrimos la pagina.

Eso esta bien, excepto que siempre se muestra el primer elemento por default. Idealmente no deberia mostrarse ninguno seleccionado.

Haz los cambios necesarios o bien en el html (seria lo correcto); o bien, en el codigo de js (no totalmente correcto, pero tambien valido).

Tiempo aproximado: 20 min

**Comment by lextes** [comment]
PR #11
