### ISSUE TITLE
Mostrar el genero seleccionado al cambiar el valor del select

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/ShowMovie#9]
Ok, la pagina ya va tomando mas forma. Ahora seria bueno que cuando el usuario hace clic sobre uno de los generos, el nombre de este, apareciera en el elemento `span` que esta al lado del siguiente:

`<p>You selected genre</p>`

Haz los cambios necesarios en html y en js para aplicar esta super inovacion :smile:

**Comment by mauleyzaola** [comment]
@lextes bien este era facil. Aun sigo en el cine

**Comment by mauleyzaola** [comment]
tiempo estimado: 30 min

disculpa que no haya puesto el estimado en su momento

**Comment by mauleyzaola** [comment]
```
dropdown.onchange=function(){
    /// que falta aqui?
}
```

**Comment by lextes** [comment]
PR #12
